PATH:
  IMG_TARGET: /home/hma/ros_ws/src/5_skills/empty_space_estimation/io/input/input.jpg # 検出したい画像を保存するディレクトリ
  IMG_MASK: /home/hma/ros_ws/src/5_skills/empty_space_estimation/io/output/mask.jpg # 検出結果の画像を保存するディレクトリ
  IMG_ADD_NUMBERS: /home/hma/ros_ws/src/5_skills/empty_space_estimation/io/output/add_number.jpg # 検出結果の画像を保存するディレクトリ
MODEL:
  PRO: gemini-2.5-pro-exp-03-25
  PRO_PREVIEW: gemini-2.5-pro-preview-06-05
  FLASH_25: gemini-2.5-flash-preview-05-20
  FLASH_20: gemini-2.0-flash


